;; Exercise 1.14.  Draw the tree illustrating the process generated by the
;; count-change procedure of section 1.2.2 in making change for 11 cents. What are
;; the orders of growth of the space and number of steps used by this process as
;; the amount to be changed increases?
;;                          (cc 11 5)
;;                         /         \
;;                   (cc -39 5)   (cc 11 4)-----------\
;;                  /            /                     \
;;                 0         (cc -14 4)             (cc 11 3)---------------------\
;;                           /                     /                               \
;;                          0           /------(cc 1 3)                       (cc 11 2)----------------------------\
;;                                     /           \                              /                                 \
;;                                 (cc -9 3)    (cc 1 2)                      (cc 6 2)                           (cc 11 1)
;;                                   /          /     \                        /      \(skipping steps)          /        \
;;                                  0    (cc -4 2)    (cc 1 1)             (cc 1 2)   (cc 6 1)            (cc 10 1)     (cc 11 0)
;;                                      /            /       \             /      \          \            /       \           \
;;                                     0         (cc 0 1)    (cc 1 0)  (cc -4 2)  (cc 1 1)    1       (cc 9 1)    (cc 10 0)     0
;;                                               /            \        /         /      \            /      \           \
;;                                              1              0      0     (cc 0 1)  (cc 1 0)   (cc 8 1)    (cc 9 0)     0
;;                                                                            /           \       /       \           \
;;                                                                           1             0   (cc 7 1)   (cc 7 0)     0
;;                                                                                             /       \          \ 
;;                                                                                           (cc 6 1) (cc 6 0)     0
;;                                                                                           ...............
;;                                                                                           /           \
;;                                                                                        (cc 1 1)     (cc 2 0)
;;                                                                                       /       \             \
;;                                                                                     (cc 0 1)  (cc 1 0)       0
;;                                                                                     /             \
;;                                                                                    1              0
;;
;; The order of growth in terms of space is amount/smallest coin
;;
;; The order of growth in terms of steps:
;;
;; When we have one coin - 1 the order of growth is 2n or just n because for
;; each amount we are making two calls to cc and we do this n times.
;; (cc 11 1) is a good example of what I just mentioned. 
;;
;; When we have two coins - 5 and 1 the order of growth is n^2.
;; Because:
;; (cc 100 2) will result to:
;; (cc 95 2) (cc 100 1)
;; (cc 90 2) (cc 95 1)
;; (cc 85 2) (cc 90 1)
;; ... and so on ...
;; For every amount we are calling cc with one coin.
;; Which is equal to: n + (n - 5) + (n - 2x5) + (n - 3x5) ... (n - (n/5)x5)
;; This is an arithmetic progression and the formula to find it's sum is:
;; S = n(an + a1)/2, where an = n and a1 = n - (n/5)x5 =>
;; S = n(n + a1)/2 = (n^2 + n^a1)/2 => n^2
;; (I didn't bother to replace a1 because it's not relevant)
;;
;; When we have three coins - 10, 5 and 1 the order of growth is n^3
;; Because:
;; (cc 100 3) will result to:
;; (cc 90 3) (cc 100 2)
;; (cc 80 3) (cc 90 2)
;; (cc 70 3) (cc 80 2)
;; ... and so on ...
;; For every amount we are calling cc with two coins.
;; Which is equal to: n^2 + (n - 10)^2 + (n - 2x10)^2 + (n - 3x10)^2 + .. + (n - (n/10)x10)^2
;; If we exapnd the equation above we should have n^2 n/10 times which means we can re-write it
;; as n/10xn^2 ... which gives us n^3 ...
;; 
;; For 4 and 5 coins should be analogous and the order of grown in terms of steps
;; for count-change should be O(n^5)
