;; Exercise 3.11. In section 3.2.3 we saw how the environment model described
;; the behavior of procedures with local state. Now we have seen how internal
;; definitions work. A typical message-passing procedure contains both of these
;; aspects. Consider the bank account procedure of section 3.1.1:
;;
;; (define (make-account balance)
;;   (define (withdraw amount)
;;     (if (>= balance amount)
;;         (begin (set! balance (- balance amount))
;;                balance)
;;         "Insufficient funds"))
;;   (define (deposit amount)
;;     (set! balance (+ balance amount))
;;     balance)
;;   (define (dispatch m)
;;     (cond ((eq? m 'withdraw) withdraw)
;;           ((eq? m 'deposit) deposit)
;;           (else (error "Unknown request -- MAKE-ACCOUNT"
;;                        m))))
;;   dispatch)
;;
;; Show the environment structure generated by the sequence of interactions
;;
;; (define acc (make-account 50))
;;
;; ((acc 'deposit) 40)
;; ;Value: 90
;;
;; ((acc 'withdraw) 60)
;; ;Value: 30
;;
;; Where is the local state for acc kept? Suppose we define another account
;;
;; (define acc2 (make-account 100))
;;
;; How are the local states for the two accounts kept distinct? Which parts of
;; the environment structure are shared between acc and acc2?


;; State 0: Initial state
;;
;; global-env: +----------------------------------------------------------------------------------------+
;;             | make-account ---------------------------------------------------------------------+    |
;;             |                                                                                   |    |
;;             |                                                                                   |    |<-----------+
;;             |                                                                                   |    |            |
;;             +-----------------------------------------------------------------------------------|----+            |
;;                                                                                                 v                 |
;;                                                                                             +-------------------+-|-+
;;                                                                                             | make-account body | | |
;;                                                                                             +-------------------+---+
;;
;;
;; State 1: After evaluating `(define acc (make-ccount 50))`
;;
;; global-env: +----------------------------------------------------------------------------------------+
;;             | make-account ---------------------------------------------------------------------+    |
;;             | acc ----------+                                                                   |    |
;;             |               |                                                                   |    |<-----------+
;;             |               |                                                                   |    |            |
;;             +---------------|-------------------------------------------------------------------|----+            |
;;                             |                                                                   v                 |
;;                             |              (created on eval of (make-account 50)            +-------------------+-|-+
;;                             |                           E1 +-------------------+            | make-account body | | |
;;                             |                              | balance: 50       |            +-------------------+---+
;;                             |                              |                   |<-------------------- +
;;                             |                              | withdraw: ----------------+              |
;;                             |                              | deposit: ------+  |       |              |
;;                             |                 +----------- | dispatch:      |  |       |              |
;;                             |                 |            +----------------|--+       |              |
;;                             |                 |                ^            | ^        |              |
;;                             |                 |                |            | |        v              |
;;                             |                 |      +---------+            | |     +---------------+-|-+
;;                             |                 |      |                      | |     | withdraw body | | |
;;                             |                 |      |                      | |     +---------------+---+
;;                             |                 |      |                      v |
;;                             |                 |      |      +---------------+-|-+
;;                             |                 |      |      | depobsit body | | |
;;                             |                 |      |      +---------------+---+
;;                             |                 |      |
;;                             |                 v      |
;;                             |      +---------------+-|-+
;;                             +----->| dispatch body | | |
;;                                    +---------------+---+
;;
;;
;;
;;
;; State 2: During and after evaluating `((acc 'deposit) 40)`
;;
;; global-env: +----------------------------------------------------------------------------------------+
;;             | make-account ---------------------------------------------------------------------+    |
;;             | acc ----------+                                                                   |    |
;;             |               |                                                                   |    |<-----------+
;;             |               |                                                                   |    |            |
;;             +---------------|-------------------------------------------------------------------|----+            |
;;                             |                                                                   v                 |
;;                             |              (created on eval of (make-account 50)            +-------------------+-|-+
;;                             |                           E1 +-------------------+            | make-account body | | |
;;                             |                              | balance: 50->90   |            +-------------------+---+
;;                             |                              |                   |<-------------------- +----------+
;;                             |                              | withdraw: ----------------+              |          |
;;                             |                              | deposit: ------+  |       |              |          |
;;                             |                 +----------- | dispatch:      |  |       |              |          |
;;                             |                 |            +----------------|--+       |              |          |
;;                             |                 |                ^            | ^        |              |          |
;;                             |                 |                |            | |        v              |          |
;;                             |                 |      +---------+            | |     +---------------+-|-+        |
;;                             |                 |      |                      | |     | withdraw body | | |        |
;;                             |                 |      |                      | |     +---------------+---+        |
;;                             |                 |      |                      v |                                  |
;;                             |                 |      |      +---------------+-|-+                                |
;;                             |                 |      |      | deposit body  | | |                                |
;;                             |                 |      |      +---------------+---+                                |
;;                             |                 |      |                                                           |
;;                             |                 v      |                                                           |
;;                             |      +---------------+-|-+                                                         |
;;                             +----->| dispatch body | | |                                                         |
;;                                    +---------------+---+                                                         |
;;                                                                                                                  |
;;                                                                                                                  |
;;                                                                           (created on eval of `(acc 'deposit')`) |
;;                                                                                            E2 +-----------+      |
;;                                                                                               |m: deposit |>-----+
;;                                                                                               +-----------+      |
;;                                                                                                                  |
;;                                                                           (created on eval of `(deposit 40)`)    |
;;                                                                                            E3 +-----------+      |
;;                                                                                               |amount: 40 |>-----+
;;                                                                                               +-----------+
;;                                                        <at this point the body deposit of body is executed and it will set the balance var in E1>
;;
;; After the completion of ((acc 'deposit') 40) E2 and E3 will disappear.
;; As per section "3.2.3 Frames as the Repository of Local State" of the book:
;; > The frame that binds amount (in which we executed the code that changed
;;   balance) is no longer relevant, since the procedure call that constructed it
;;   has terminated, and there are no pointers to that frame from other parts of
;;   the environment.
;;
;;
;;
;;
;; State 3: During and after evaluating `((acc 'withdraw) 60)`
;;
;; Here the situation is similar to "State 2" - new E2 and E3(but for withdraw)
;; envs will be created and balance in E1 will be modified.
;;
;;
;; State 4: (define acc2 (make-account 100))
;;
;; A new E2 identitcal to E1 will be created and the local state of acc is kept
;; in E1 whereas the local state of acc2 is kept in E2.
;;
;; Only the global env is shared between acc & acc2
